
TUNISIA.working.dir=.\\PROJECT
KSA.working.dir=.\\workingdir\\ksa

HWS.ELEC.en=Tankless electric DHW system
HWS.GAS.en=Tank gas-fired DHW system

cmbBldgSystem.PVAVS.en=Packaged Variable Air Volume System
cmbBldgSystem.SSWB.en=Split System with Baseboard
cmbBldgSystem.RS.en=Residential System
cmbBldgSystem.FCS.en=Fan Coil System
cmbBldgSystem.VAVS.en=Variable Air Volume Systemm

bldgcat.office.en=Office
bldgcat.hotel.en=Hotel
bldgcat.hospital.en=Hospital
bldgcat.apartment.en=Apartment
bldgcat.villa.en=Villa

contactflr.ground.en=ground
contactflr.ac.en=condition
contactflr.nonac.en=uncondition

	
	
	
	

